export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type UserRole = "adm_master" | "clinic_admin" | "staff";

export type Database = {
  public: {
    Tables: {
      clinics: {
        Row: {
          id: string;
          name: string;
          slug: string | null;
          active: boolean | null;
          phone: string | null;
          whatsapp: string | null;
          email: string | null;
          cnpj: string | null;
          address: string | null;
          status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug?: string | null;
          active?: boolean | null;
          phone?: string | null;
          whatsapp?: string | null;
          email?: string | null;
          cnpj?: string | null;
          address?: string | null;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string | null;
          active?: boolean | null;
          phone?: string | null;
          whatsapp?: string | null;
          email?: string | null;
          cnpj?: string | null;
          address?: string | null;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      employees: {
        Row: {
          id: string;
          clinic_id: string | null;
          name: string;
          phone: string | null;
          whatsapp: string | null;
          email: string | null;
          role: string | null;
          system_access: boolean;
          login_email: string | null;
          temporary_password: string | null;
          commission_type: string | null;
          commission_value: number | null;
          status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          clinic_id?: string | null;
          name: string;
          phone?: string | null;
          whatsapp?: string | null;
          email?: string | null;
          role?: string | null;
          system_access?: boolean;
          login_email?: string | null;
          temporary_password?: string | null;
          commission_type?: string | null;
          commission_value?: number | null;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          clinic_id?: string | null;
          name?: string;
          phone?: string | null;
          whatsapp?: string | null;
          email?: string | null;
          role?: string | null;
          system_access?: boolean;
          login_email?: string | null;
          temporary_password?: string | null;
          commission_type?: string | null;
          commission_value?: number | null;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      services: {
        Row: {
          id: string;
          clinic_id: string | null;
          name: string;
          internal_code: string | null;
          category_id: string | null;
          category: string | null;
          description: string | null;
          type: string | null;
          price: number | null;
          duration_minutes: number | null;
          default_duration_minutes: number | null;
          break_minutes: number | null;
          default_price: number | null;
          promotional_price: number | null;
          required_credits: number;
          attendance_type: string;
          allows_package: boolean;
          commission_type: string | null;
          commission_value: number | null;
          color: string | null;
          image_url: string | null;
          is_group: boolean;
          participant_limit: number | null;
          requires_medical_record: boolean;
          requires_authorization: boolean;
          pre_service_instructions: string | null;
          post_service_instructions: string | null;
          required_materials: string | null;
          billing_type: string;
          service_mode: string;
          priority: string;
          classification: string | null;
          requires_consent_form: boolean;
          requires_photos: boolean;
          requires_attachment: boolean;
          is_initial_assessment: boolean;
          suggested_sessions: number | null;
          suggested_price: number | null;
          suggested_discount: number | null;
          room_required: string | null;
          equipment_required: string | null;
          preparation_minutes: number | null;
          cleanup_minutes: number | null;
          created_by: string | null;
          updated_by: string | null;
          status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          clinic_id?: string | null;
          name: string;
          internal_code?: string | null;
          category_id?: string | null;
          category?: string | null;
          description?: string | null;
          type?: string | null;
          price?: number | null;
          duration_minutes?: number | null;
          default_duration_minutes?: number | null;
          break_minutes?: number | null;
          default_price?: number | null;
          promotional_price?: number | null;
          required_credits?: number;
          attendance_type?: string;
          allows_package?: boolean;
          commission_type?: string | null;
          commission_value?: number | null;
          color?: string | null;
          image_url?: string | null;
          is_group?: boolean;
          participant_limit?: number | null;
          requires_medical_record?: boolean;
          requires_authorization?: boolean;
          pre_service_instructions?: string | null;
          post_service_instructions?: string | null;
          required_materials?: string | null;
          billing_type?: string;
          service_mode?: string;
          priority?: string;
          classification?: string | null;
          requires_consent_form?: boolean;
          requires_photos?: boolean;
          requires_attachment?: boolean;
          is_initial_assessment?: boolean;
          suggested_sessions?: number | null;
          suggested_price?: number | null;
          suggested_discount?: number | null;
          room_required?: string | null;
          equipment_required?: string | null;
          preparation_minutes?: number | null;
          cleanup_minutes?: number | null;
          created_by?: string | null;
          updated_by?: string | null;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          clinic_id?: string | null;
          name?: string;
          internal_code?: string | null;
          category_id?: string | null;
          category?: string | null;
          description?: string | null;
          type?: string | null;
          price?: number | null;
          duration_minutes?: number | null;
          default_duration_minutes?: number | null;
          break_minutes?: number | null;
          default_price?: number | null;
          promotional_price?: number | null;
          required_credits?: number;
          attendance_type?: string;
          allows_package?: boolean;
          commission_type?: string | null;
          commission_value?: number | null;
          color?: string | null;
          image_url?: string | null;
          is_group?: boolean;
          participant_limit?: number | null;
          requires_medical_record?: boolean;
          requires_authorization?: boolean;
          pre_service_instructions?: string | null;
          post_service_instructions?: string | null;
          required_materials?: string | null;
          billing_type?: string;
          service_mode?: string;
          priority?: string;
          classification?: string | null;
          requires_consent_form?: boolean;
          requires_photos?: boolean;
          requires_attachment?: boolean;
          is_initial_assessment?: boolean;
          suggested_sessions?: number | null;
          suggested_price?: number | null;
          suggested_discount?: number | null;
          room_required?: string | null;
          equipment_required?: string | null;
          preparation_minutes?: number | null;
          cleanup_minutes?: number | null;
          created_by?: string | null;
          updated_by?: string | null;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      service_categories: {
        Row: {
          id: string;
          clinic_id: string | null;
          name: string;
          description: string | null;
          color: string | null;
          status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          clinic_id?: string | null;
          name: string;
          description?: string | null;
          color?: string | null;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          clinic_id?: string | null;
          name?: string;
          description?: string | null;
          color?: string | null;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      service_professionals: {
        Row: {
          id: string;
          service_id: string;
          employee_id: string;
          is_primary: boolean;
          commission_type: string | null;
          commission_value: number | null;
          status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          service_id: string;
          employee_id: string;
          is_primary?: boolean;
          commission_type?: string | null;
          commission_value?: number | null;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          service_id?: string;
          employee_id?: string;
          is_primary?: boolean;
          commission_type?: string | null;
          commission_value?: number | null;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      service_packages: {
        Row: {
          id: string;
          clinic_id: string | null;
          name: string;
          description: string | null;
          sessions_quantity: number;
          total_price: number | null;
          price_per_session: number | null;
          validity_days: number | null;
          allow_freeze: boolean;
          allow_renewal: boolean;
          allow_custom_patient_package: boolean;
          uses_credits: boolean;
          contracted_credits: number;
          used_credits: number;
          available_credits: number;
          reversed_credits: number;
          expired_credits: number;
          status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          clinic_id?: string | null;
          name: string;
          description?: string | null;
          sessions_quantity?: number;
          total_price?: number | null;
          price_per_session?: number | null;
          validity_days?: number | null;
          allow_freeze?: boolean;
          allow_renewal?: boolean;
          allow_custom_patient_package?: boolean;
          uses_credits?: boolean;
          contracted_credits?: number;
          used_credits?: number;
          available_credits?: number;
          reversed_credits?: number;
          expired_credits?: number;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          clinic_id?: string | null;
          name?: string;
          description?: string | null;
          sessions_quantity?: number;
          total_price?: number | null;
          price_per_session?: number | null;
          validity_days?: number | null;
          allow_freeze?: boolean;
          allow_renewal?: boolean;
          allow_custom_patient_package?: boolean;
          uses_credits?: boolean;
          contracted_credits?: number;
          used_credits?: number;
          available_credits?: number;
          reversed_credits?: number;
          expired_credits?: number;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      patient_packages: {
        Row: {
          id: string;
          clinic_id: string;
          patient_id: string;
          service_id: string;
          employee_id: string | null;
          contracted_sessions: number;
          completed_sessions: number;
          remaining_sessions: number;
          unit_session_value: number;
          discount_percent: number;
          subtotal_value: number;
          discount_value: number;
          total_value: number;
          purchase_date: string;
          expiration_date: string | null;
          payment_method: string;
          status: string;
          sale_responsible_id: string | null;
          notes: string | null;
          agenda_integration_status: string;
          finance_integration_status: string;
          future_revenue_status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          clinic_id: string;
          patient_id: string;
          service_id: string;
          employee_id?: string | null;
          contracted_sessions?: number;
          completed_sessions?: number;
          remaining_sessions?: number;
          unit_session_value?: number;
          discount_percent?: number;
          subtotal_value?: number;
          discount_value?: number;
          total_value?: number;
          purchase_date?: string;
          expiration_date?: string | null;
          payment_method?: string;
          status?: string;
          sale_responsible_id?: string | null;
          notes?: string | null;
          agenda_integration_status?: string;
          finance_integration_status?: string;
          future_revenue_status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          clinic_id?: string;
          patient_id?: string;
          service_id?: string;
          employee_id?: string | null;
          contracted_sessions?: number;
          completed_sessions?: number;
          remaining_sessions?: number;
          unit_session_value?: number;
          discount_percent?: number;
          subtotal_value?: number;
          discount_value?: number;
          total_value?: number;
          purchase_date?: string;
          expiration_date?: string | null;
          payment_method?: string;
          status?: string;
          sale_responsible_id?: string | null;
          notes?: string | null;
          agenda_integration_status?: string;
          finance_integration_status?: string;
          future_revenue_status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      service_package_items: {
        Row: {
          id: string;
          package_id: string;
          service_id: string;
          sessions_quantity: number;
          credits_quantity: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          package_id: string;
          service_id: string;
          sessions_quantity?: number;
          credits_quantity?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          package_id?: string;
          service_id?: string;
          sessions_quantity?: number;
          credits_quantity?: number;
          created_at?: string;
        };
        Relationships: [];
      };
      service_discounts: {
        Row: {
          id: string;
          clinic_id: string | null;
          service_id: string | null;
          package_id: string | null;
          name: string;
          sessions_quantity: number;
          discount_type: string;
          discount_value: number;
          original_price: number | null;
          final_price: number | null;
          price_per_session: number | null;
          total_savings: number | null;
          can_override_during_sale: boolean;
          visible_to_professional: boolean;
          status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          clinic_id?: string | null;
          service_id?: string | null;
          package_id?: string | null;
          name: string;
          sessions_quantity?: number;
          discount_type?: string;
          discount_value?: number;
          original_price?: number | null;
          final_price?: number | null;
          price_per_session?: number | null;
          total_savings?: number | null;
          can_override_during_sale?: boolean;
          visible_to_professional?: boolean;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          clinic_id?: string | null;
          service_id?: string | null;
          package_id?: string | null;
          name?: string;
          sessions_quantity?: number;
          discount_type?: string;
          discount_value?: number;
          original_price?: number | null;
          final_price?: number | null;
          price_per_session?: number | null;
          total_savings?: number | null;
          can_override_during_sale?: boolean;
          visible_to_professional?: boolean;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      commercial_rules: {
        Row: {
          id: string;
          clinic_id: string | null;
          name: string;
          rule_type: string;
          coupon_code: string | null;
          discount_type: string | null;
          discount_value: number | null;
          max_discount_admin: number | null;
          max_discount_manager: number | null;
          max_discount_professional: number | null;
          start_date: string | null;
          end_date: string | null;
          status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          clinic_id?: string | null;
          name: string;
          rule_type: string;
          coupon_code?: string | null;
          discount_type?: string | null;
          discount_value?: number | null;
          max_discount_admin?: number | null;
          max_discount_manager?: number | null;
          max_discount_professional?: number | null;
          start_date?: string | null;
          end_date?: string | null;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          clinic_id?: string | null;
          name?: string;
          rule_type?: string;
          coupon_code?: string | null;
          discount_type?: string | null;
          discount_value?: number | null;
          max_discount_admin?: number | null;
          max_discount_manager?: number | null;
          max_discount_professional?: number | null;
          start_date?: string | null;
          end_date?: string | null;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      treatment_goals: {
        Row: {
          id: string;
          name: string;
          description: string | null;
          status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          description?: string | null;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          description?: string | null;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      treatment_protocols: {
        Row: {
          id: string;
          clinic_id: string | null;
          name: string;
          objective: string | null;
          goal_id: string | null;
          recommended_sessions: number | null;
          recommended_interval_days: number | null;
          status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          clinic_id?: string | null;
          name: string;
          objective?: string | null;
          goal_id?: string | null;
          recommended_sessions?: number | null;
          recommended_interval_days?: number | null;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          clinic_id?: string | null;
          name?: string;
          objective?: string | null;
          goal_id?: string | null;
          recommended_sessions?: number | null;
          recommended_interval_days?: number | null;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      treatment_protocol_steps: {
        Row: {
          id: string;
          protocol_id: string;
          service_id: string | null;
          step_order: number;
          title: string;
          recommended_sessions: number | null;
          recommended_interval_days: number | null;
          notes: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          protocol_id: string;
          service_id?: string | null;
          step_order?: number;
          title: string;
          recommended_sessions?: number | null;
          recommended_interval_days?: number | null;
          notes?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          protocol_id?: string;
          service_id?: string | null;
          step_order?: number;
          title?: string;
          recommended_sessions?: number | null;
          recommended_interval_days?: number | null;
          notes?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      service_resources: {
        Row: {
          id: string;
          service_id: string;
          room: string | null;
          equipment: string | null;
          stretcher_required: boolean;
          specific_device: string | null;
          materials: string | null;
          preparation_minutes: number | null;
          cleanup_minutes: number | null;
          status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          service_id: string;
          room?: string | null;
          equipment?: string | null;
          stretcher_required?: boolean;
          specific_device?: string | null;
          materials?: string | null;
          preparation_minutes?: number | null;
          cleanup_minutes?: number | null;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          service_id?: string;
          room?: string | null;
          equipment?: string | null;
          stretcher_required?: boolean;
          specific_device?: string | null;
          materials?: string | null;
          preparation_minutes?: number | null;
          cleanup_minutes?: number | null;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      service_required_documents: {
        Row: {
          id: string;
          service_id: string;
          requires_consent_form: boolean;
          requires_authorization: boolean;
          requires_before_after_photos: boolean;
          requires_attachment: boolean;
          requires_medical_record: boolean;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          service_id: string;
          requires_consent_form?: boolean;
          requires_authorization?: boolean;
          requires_before_after_photos?: boolean;
          requires_attachment?: boolean;
          requires_medical_record?: boolean;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          service_id?: string;
          requires_consent_form?: boolean;
          requires_authorization?: boolean;
          requires_before_after_photos?: boolean;
          requires_attachment?: boolean;
          requires_medical_record?: boolean;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      internal_notifications: {
        Row: {
          id: string;
          clinic_id: string | null;
          service_id: string | null;
          employee_id: string | null;
          title: string;
          message: string;
          notification_type: string;
          whatsapp_template: string | null;
          status: string;
          created_at: string;
          read_at: string | null;
        };
        Insert: {
          id?: string;
          clinic_id?: string | null;
          service_id?: string | null;
          employee_id?: string | null;
          title: string;
          message: string;
          notification_type?: string;
          whatsapp_template?: string | null;
          status?: string;
          created_at?: string;
          read_at?: string | null;
        };
        Update: {
          id?: string;
          clinic_id?: string | null;
          service_id?: string | null;
          employee_id?: string | null;
          title?: string;
          message?: string;
          notification_type?: string;
          whatsapp_template?: string | null;
          status?: string;
          created_at?: string;
          read_at?: string | null;
        };
        Relationships: [];
      };
      service_audit_logs: {
        Row: {
          id: string;
          service_id: string | null;
          action: string;
          field_name: string | null;
          old_value: string | null;
          new_value: string | null;
          changed_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          service_id?: string | null;
          action: string;
          field_name?: string | null;
          old_value?: string | null;
          new_value?: string | null;
          changed_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          service_id?: string | null;
          action?: string;
          field_name?: string | null;
          old_value?: string | null;
          new_value?: string | null;
          changed_by?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      professional_service_commissions: {
        Row: {
          id: string;
          professional_id: string;
          service_id: string;
          attendance_type: string;
          modality: string;
          group_calculation_mode: string;
          base_price: number | null;
          commission_type: string;
          commission_value: number;
          estimated_amount: number;
          active: boolean;
          notes: string | null;
          created_by: string | null;
          updated_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          professional_id: string;
          service_id: string;
          attendance_type?: string;
          modality?: string;
          group_calculation_mode?: string;
          base_price?: number | null;
          commission_type?: string;
          commission_value?: number;
          estimated_amount?: number;
          active?: boolean;
          notes?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          professional_id?: string;
          service_id?: string;
          attendance_type?: string;
          modality?: string;
          group_calculation_mode?: string;
          base_price?: number | null;
          commission_type?: string;
          commission_value?: number;
          estimated_amount?: number;
          active?: boolean;
          notes?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      professional_service_commission_history: {
        Row: {
          id: string;
          commission_id: string | null;
          service_id: string | null;
          professional_id: string | null;
          old_value: number | null;
          new_value: number | null;
          changed_by: string | null;
          reason: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          commission_id?: string | null;
          service_id?: string | null;
          professional_id?: string | null;
          old_value?: number | null;
          new_value?: number | null;
          changed_by?: string | null;
          reason?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          commission_id?: string | null;
          service_id?: string | null;
          professional_id?: string | null;
          old_value?: number | null;
          new_value?: number | null;
          changed_by?: string | null;
          reason?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      user_permissions: {
        Row: {
          id: string;
          employee_id: string;
          module_key: string;
          can_view: boolean;
          can_create: boolean;
          can_edit: boolean;
          can_delete: boolean;
          can_toggle: boolean;
          can_export: boolean;
          can_import: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          employee_id: string;
          module_key: string;
          can_view?: boolean;
          can_create?: boolean;
          can_edit?: boolean;
          can_delete?: boolean;
          can_toggle?: boolean;
          can_export?: boolean;
          can_import?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          employee_id?: string;
          module_key?: string;
          can_view?: boolean;
          can_create?: boolean;
          can_edit?: boolean;
          can_delete?: boolean;
          can_toggle?: boolean;
          can_export?: boolean;
          can_import?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      appointments: {
        Row: {
          id: string;
          clinic_id: string;
          patient_id: string;
          employee_id: string;
          service_id: string;
          appointment_date: string;
          start_time: string;
          end_time: string | null;
          notes: string | null;
          status: string;
          medical_record_id: string | null;
          performed_at: string | null;
          finance_integration_status: string;
          commission_integration_status: string;
          package_session_status: string;
          sessions_contracted: number;
          sessions_completed: number;
          appointment_type: string;
          appointment_origin: string;
          original_appointment_id: string | null;
          is_billable: boolean;
          consumes_package_session: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          clinic_id: string;
          patient_id: string;
          employee_id: string;
          service_id: string;
          appointment_date: string;
          start_time: string;
          end_time?: string | null;
          notes?: string | null;
          status?: string;
          medical_record_id?: string | null;
          performed_at?: string | null;
          finance_integration_status?: string;
          commission_integration_status?: string;
          package_session_status?: string;
          sessions_contracted?: number;
          sessions_completed?: number;
          appointment_type?: string;
          appointment_origin?: string;
          original_appointment_id?: string | null;
          is_billable?: boolean;
          consumes_package_session?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          clinic_id?: string;
          patient_id?: string;
          employee_id?: string;
          service_id?: string;
          appointment_date?: string;
          start_time?: string;
          end_time?: string | null;
          notes?: string | null;
          status?: string;
          medical_record_id?: string | null;
          performed_at?: string | null;
          finance_integration_status?: string;
          commission_integration_status?: string;
          package_session_status?: string;
          sessions_contracted?: number;
          sessions_completed?: number;
          appointment_type?: string;
          appointment_origin?: string;
          original_appointment_id?: string | null;
          is_billable?: boolean;
          consumes_package_session?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      appointment_participants: {
        Row: {
          id: string;
          appointment_id: string;
          patient_id: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          appointment_id: string;
          patient_id: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          appointment_id?: string;
          patient_id?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      schedule_blocks: {
        Row: {
          id: string;
          clinic_id: string;
          employee_id: string | null;
          block_date: string;
          block_type: string;
          start_time: string | null;
          end_time: string | null;
          reason: string | null;
          status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          clinic_id: string;
          employee_id?: string | null;
          block_date: string;
          block_type?: string;
          start_time?: string | null;
          end_time?: string | null;
          reason?: string | null;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          clinic_id?: string;
          employee_id?: string | null;
          block_date?: string;
          block_type?: string;
          start_time?: string | null;
          end_time?: string | null;
          reason?: string | null;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      patient_session_history: {
        Row: {
          id: string;
          clinic_id: string;
          patient_id: string;
          employee_id: string | null;
          service_id: string | null;
          appointment_id: string | null;
          session_date: string;
          status: string;
          notes: string | null;
          finance_integration_status: string;
          commission_integration_status: string;
          package_session_status: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          clinic_id: string;
          patient_id: string;
          employee_id?: string | null;
          service_id?: string | null;
          appointment_id?: string | null;
          session_date: string;
          status?: string;
          notes?: string | null;
          finance_integration_status?: string;
          commission_integration_status?: string;
          package_session_status?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          clinic_id?: string;
          patient_id?: string;
          employee_id?: string | null;
          service_id?: string | null;
          appointment_id?: string | null;
          session_date?: string;
          status?: string;
          notes?: string | null;
          finance_integration_status?: string;
          commission_integration_status?: string;
          package_session_status?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      medical_records: {
        Row: {
          id: string;
          clinic_id: string | null;
          appointment_id: string | null;
          patient_id: string | null;
          employee_id: string | null;
          title: string;
          complaint: string | null;
          history: string | null;
          conduct: string | null;
          evolution: string | null;
          notes: string | null;
          status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          clinic_id?: string | null;
          appointment_id?: string | null;
          patient_id?: string | null;
          employee_id?: string | null;
          title: string;
          complaint?: string | null;
          history?: string | null;
          conduct?: string | null;
          evolution?: string | null;
          notes?: string | null;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          clinic_id?: string | null;
          appointment_id?: string | null;
          patient_id?: string | null;
          employee_id?: string | null;
          title?: string;
          complaint?: string | null;
          history?: string | null;
          conduct?: string | null;
          evolution?: string | null;
          notes?: string | null;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      profiles: {
        Row: {
          id: string;
          clinic_id: string | null;
          full_name: string;
          role: UserRole;
          created_at: string;
        };
        Insert: {
          id: string;
          clinic_id?: string | null;
          full_name: string;
          role?: UserRole;
          created_at?: string;
        };
        Update: {
          id?: string;
          clinic_id?: string | null;
          full_name?: string;
          role?: UserRole;
          created_at?: string;
        };
        Relationships: [];
      };
      patients: {
        Row: {
          id: string;
          clinic_id: string | null;
          full_name: string;
          cpf: string | null;
          birth_date: string | null;
          phone: string | null;
          email: string | null;
          portal_access: boolean;
          login_email: string | null;
          temporary_password: string | null;
          address: string | null;
          notes: string | null;
          status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          clinic_id?: string | null;
          full_name: string;
          cpf?: string | null;
          birth_date?: string | null;
          phone?: string | null;
          email?: string | null;
          portal_access?: boolean;
          login_email?: string | null;
          temporary_password?: string | null;
          address?: string | null;
          notes?: string | null;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          clinic_id?: string | null;
          full_name?: string;
          cpf?: string | null;
          birth_date?: string | null;
          phone?: string | null;
          email?: string | null;
          portal_access?: boolean;
          login_email?: string | null;
          temporary_password?: string | null;
          address?: string | null;
          notes?: string | null;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
    };
    Views: {};
    Functions: {};
    Enums: {};
    CompositeTypes: {};
  };
};
